import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Project Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl">Hello from Project Finder</h1>
      </main>
    </div>
  );
}
